name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      # - name: Copy files
      #   run: cp -r ./src ./src


      - run: npm install

      # - name: Ensure build directory exists
      #   run: mkdir -p build

      # - run: npm run build
      - run: |
          echo @sachinSingh53:https://npm.pkg.github.com/ > .npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm publish
        # working-directory: ./src
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

