apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: production
spec:
  storageClassName: mongo-local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: production
spec:
  storageClassName: mongo-local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

